USE scada;

ALTER TABLE users
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN nickname name VARCHAR(100) NULL,
    ADD COLUMN phone VARCHAR(50) NULL AFTER name,
    ADD COLUMN role ENUM('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER') NOT NULL DEFAULT 'VIEWER' AFTER phone,
    ADD COLUMN plant_id BIGINT NULL AFTER role,
    ADD COLUMN status ENUM('ACTIVE', 'INACTIVE', 'LOCKED') NOT NULL DEFAULT 'ACTIVE' AFTER plant_id,
    ADD COLUMN note VARCHAR(500) NULL AFTER status,
    ADD COLUMN last_login_at DATETIME NULL AFTER note;

UPDATE users
SET name = email
WHERE name IS NULL OR name = '';

ALTER TABLE users
    MODIFY COLUMN name VARCHAR(100) NOT NULL;
